[colors.primary]
background = "#000000"

[font]
size = 14.0

[font.normal]
style = "Regular"
family = "MesloLGSDZ Nerd Font" 

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 10
y = 20
