import = ["/home/saroj/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[cursor]
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 10
y = 10
