#!/usr/bin/zsh

# addind the zoxide configuration
eval "$(zoxide init zsh)"

# better vim mode
# adding the zsh vi mode plugin: zvm
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
ZVM_CURSOR_STYLE_ENABLED=false

# adding fnm
zinit light "dominik-schwabe/zsh-fnm"
export ZSH_FNM_NODE_VERSION="24.3.0"
